"""add chunk compression table and explanation field to chunk

Revision ID: 080cc2939fec
Revises: 479b79a49d78
Create Date: 2025-06-28 14:55:08.195766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '080cc2939fec'
down_revision: Union[str, None] = '479b79a49d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunkcompression',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('compressed_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chunk', sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'explanation')
    op.drop_table('chunkcompression')
    # ### end Alembic commands ###
