"""add author to sourcedocument

Revision ID: 479b79a49d78
Revises: 5d324cdcc8bf
Create Date: 2025-06-11 13:53:50.814270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479b79a49d78'
down_revision: Union[str, None] = '5d324cdcc8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('sourcedocument', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sourcedocument', 'author')
    # ### end Alembic commands ###
