"""remove_user_chunk_session_table

Revision ID: ab623b7111c1
Revises: 080cc2939fec
Create Date: 2025-07-11 09:52:09.551657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab623b7111c1'
down_revision: Union[str, None] = '080cc2939fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userchunksession')
    op.create_index(op.f('ix_chunk_position'), 'chunk', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_position'), table_name='chunk')
    op.create_table('userchunksession',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('meta_text_id', sa.INTEGER(), nullable=False),
    sa.Column('last_active_chunk_id', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['last_active_chunk_id'], ['chunk.id'], ),
    sa.ForeignKeyConstraint(['meta_text_id'], ['metatext.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
